### ISSUE TITLE
Assess the security of our mainnet DAO

### ISSUE THREAD

**Issue by 0x6431346e** [AragonMesh/team#4]
Currently we have:
- 1 token manager with Gabi and I having 1 token each.
- 1 voting app with 100% quorum, 24H duration for votes.

We should have a plan in case:
- one of us has his key leaked
- one of us goes AWOL or becomes unreachable for a long time

**Comment by 0xGabi** [comment]
Solved installing two new apps in the DAO:
- 1 token manager with Daniel, I and Aragon Asociation having 1 token each.
- 1 voting app with 50% quorum, 7 days duration for votes with permission for create payments on the finance app.
